apiVersion: 1

datasources:
  - name: AStock-PostgreSQL
    type: postgres
    access: proxy
    url: astock-postgres:5432
    user: astock
    database: astock
    secureJsonData:
      password: astock123
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
